//THE AKAN APPLICATION

// Initialization Step
// Prevent data being automatically posted to a remote URL on Submit button click


// Begin by accessing the specific form we wish to prevent default submit



let akanForm = document.getElementById('akan-form')

akanForm.addEventListener('image', event=>{

  //method preventing the browser from submitting the form

      event.preventDefault()
});


//Business Logic
// 1. Declare the variable types of the name result options to be generated
//    placing them inside an array according to thier corresponding gender.

// The maleNames and femaleNames in the array are in an indexed order 
// which corresponds to the day of the week designation for each name.

const daysOfTheWeek = ['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'];

const femaleNames = ['Akosua','Adwoa','Abenaa','Akua','Yaa','Afua','Ama'];

const maleNames = ['Kwasi','Kwadwo','Kwabena','Kwaku', 'Yaw', 'Kofi','Kwame'];

// Application Logic


// 3.Formulate and hoist a Function Declaration to automatically invoke the Akan module 
//   using an event listener for on-click submit button event.

//4. Add event listener for the Submit button to output the results generated by executing 
//  its corresponding function.

